language: python
python:
- '2.7'
cache: pip
install:
- pip install -r requirements.txt
- pip install coveralls
script: nosetests --with-coverage --cover-tests --cover-erase --cover-package=threadedtree
branches:
  only:
  - master
after_success: coveralls
deploy:
  provider: pypi
  user: MS-DDOS
  password:
    secure: XjYJ0hZrBAJKrRDBtF1IuQwDdSFZXlcf2SRozK01MFKiZSlupx9FaIqVxZ83fMKgcKAII3Ab17sRU8ESfPr+i+n4BtydHCYpSj2b1ex6KcNG6TQK4f+czhjKqg0H2ii0CcoV1WYbcKO4AqX0TKwU2HgFbwL5WtbHKwgAb9hhBKudmAZG+oS/KObRhG+OkQ4AzYgcKpbooD02YPfC/HIy7mYMvntBoBdYqgTjJGKLLL/jDUDg0JMKaz3etR0ryuUMJSntN29bMDIWEGFl8cuxnxD/Fx+UeiKZjF070r5zn2xB9JrdN35FkGPbSj9MmpFrenPOSaolRkTNEFjZH/y/NH5ZQhxT2HDWuXjYpG2OleRuFNjeDgRSFNVFZvDqVPnuaGJvtjZGet452Hw8mh1DwVI/BSZEE2e1WDTpCEU91k6KX63GyN66Hilk8fouf0Y9z5DhtVRI1CEn8lRiiteA8+Ibg+cvHtKoN+mPT4fKz12ERPWh2eFdu0QzlRw3rt1rDtDBaRqd5yWQ5QRGdVicEN5EcmUZ0s+uR99iUrQ4trfNR341qru/pYWBDdDIRsBVxoSZdWhcnAAYtaP09Ynr6DKvvf2nfY6s9WIOxHMc5J/B9v0yVkLMd7/nhBNcPnTq/s3Kk2R14Rutb2x7xAXfZ34qmsoY0O4cWWfjvN3Rtko=
  on:
    branch: master
    tags: true
